INSERT INTO PIZZA_TAMANHO (DESCRICAO,VALOR,TEMPO_PREPARO) VALUES 
('Pequena', 20, 15),
('Média', 30, 20),
('Grande', 40, 25);

INSERT INTO PIZZA_SABOR (DESCRICAO,TEMPO_ADICIONAL) VALUES 
('Calabresa', 0),
('Marguerita', 0),
('Portuguesa', 5);

INSERT INTO PIZZA_PERSONALIZACAO (DESCRICAO,VALOR_ADICIONAL,TEMPO_ADICIONAL) VALUES 
('Extra bacon', 3, 0),
('Sem cebola', 0, 0),
('Borda recheada', 5, 5);